modLoader="lowcodefml"
loaderVersion="[1,)"
license="LGPL 3.0 or later"
showAsResourcePack = false

[[mods]]
modId="betteraddserver"
version="${version}"
displayName="Better \"Add Server\""
description="Small quality-of-life-enhancements for the \"Add Server\" menu "
authors="Player005"
logoFile = "assets/betteraddserver/icon.png"
logoBlur = false

[[mixins]]
config="betteraddserver.mixins.json"