name: build-release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Brachyura directory
        uses: actions/cache@v2
        with:
          path: |
            .brachyura
            ~/.brachyura
          key: ${{ runner.os }}-brachyura-${{ hashFiles('**/Buildscript.java') }}
          restore-keys: ${{ runner.os }}-brachyura

      - name: Build with Brachyura
        run: java -Diris.release=true -jar brachyura-bootstrap-0.jar build

      - name: Upload artifacts to Modrinth, Curseforge and GitHub
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: s4DtR8IM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset

          //curseforge-id: -
          //curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/!(*-@(dev|sources|all)).jar

          version-type: release

          loaders: fabric quilt

          dependencies: sodium | depends | *

          version-resolver: latest
